# Generated by Django 5.1.4 on 2025-01-25 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Female',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_female', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_male', models.CharField(blank=True, max_length=100, null=True)),
                ('girls', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pages.female')),
            ],
        ),
    ]
